#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Interactive year lens UI for the real-data WeRead Pages archive.

Consumes existing embedded D / D.insights / E data only. No new inference and no
raw note text.
"""

CSS = r'''
.year-lens-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;flex-wrap:wrap}.year-switch{display:flex;gap:6px;flex-wrap:wrap}.year-btn{border:1px solid var(--line);background:var(--paper);color:var(--muted);border-radius:999px;padding:7px 11px;font:inherit;font-size:12px;cursor:pointer}.year-btn.active{background:var(--ink);color:var(--paper);border-color:var(--ink)}.year-kpi-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin:16px 0}.year-kpi{border:1px solid var(--line);border-radius:15px;padding:13px}.year-kpi span{display:block;color:var(--muted);font-size:10px}.year-kpi b{display:block;font-size:19px;margin-top:5px}.year-lens-body{display:grid;grid-template-columns:1.25fr .75fr;gap:16px}.year-months,.year-evidence{border:1px solid var(--line);border-radius:16px;padding:14px}.year-month-bars{height:185px;display:grid;grid-template-columns:repeat(12,1fr);gap:7px;align-items:end}.year-month-col{height:100%;display:grid;grid-template-rows:1fr auto auto;gap:5px;align-items:end;text-align:center}.year-month-wrap{height:135px;display:flex;align-items:end;justify-content:center;position:relative}.year-month-bar{width:min(26px,72%);border-radius:7px 7px 2px 2px;background:var(--accent2);min-height:2px;position:relative}.year-month-note{position:absolute;top:-15px;left:50%;transform:translateX(-50%);font-size:8px;color:var(--muted);white-space:nowrap}.year-month-val{font-size:9px;color:var(--muted)}.year-month-lab{font-size:9px}.year-evidence h3,.year-months h3{font-size:13px;margin:0 0 10px}.year-focus-chips{display:flex;gap:7px;flex-wrap:wrap;margin-bottom:12px}.year-focus-chip{border:1px solid var(--line);border-radius:999px;padding:6px 9px;font-size:10px}.year-focus-chip b{color:var(--accent)}.year-detail-list{display:grid;gap:8px;font-size:11px}.year-detail-row{display:flex;justify-content:space-between;gap:12px;border-bottom:1px solid var(--line);padding-bottom:7px}.year-detail-row span:first-child{color:var(--muted)}.year-book-strip{display:grid;grid-template-columns:repeat(6,1fr);gap:10px;margin-top:14px}.year-book-card{min-width:0;border:1px solid var(--line);border-radius:14px;padding:8px}.year-book-cover{aspect-ratio:2/3;border-radius:8px;background:var(--line);overflow:hidden}.year-book-cover img{width:100%;height:100%;object-fit:cover}.year-book-card b{display:block;font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;margin-top:6px}.year-book-card small{display:block;font-size:9px;color:var(--muted);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.year-book-card em{display:block;font-size:9px;color:var(--accent);font-style:normal;margin-top:3px}
@media(max-width:850px){.year-lens-body{grid-template-columns:1fr}.year-kpi-grid{grid-template-columns:repeat(3,1fr)}.year-book-strip{grid-template-columns:repeat(4,1fr)}}@media(max-width:520px){.year-kpi-grid{grid-template-columns:repeat(2,1fr)}.year-book-strip{grid-template-columns:repeat(3,1fr)}.year-month-bars{gap:3px}.year-month-note{display:none}}
'''

HTML = r'''
  <article class="card wide" id="year-lens"><div class="year-lens-head"><div><div class="section-kicker">Year lens</div><h2 style="margin:0">年度透镜</h2><p class="subtle" style="margin:5px 0 0">把长期档案切成一年一页：时长、笔记、关注类别、作者和官方偏好书联动查看。</p></div><div class="year-switch" id="yearSwitch"></div></div><div class="year-kpi-grid" id="yearKpis"></div><div class="year-lens-body"><div class="year-months"><h3>12 个月阅读节奏 <span class="subtle">柱 = 小时；柱顶 = 笔记</span></h3><div class="year-month-bars" id="yearMonthBars"></div></div><div class="year-evidence"><h3>年度证据摘要</h3><div class="year-focus-chips" id="yearFocus"></div><div class="year-detail-list" id="yearDetails"></div></div></div><div class="title" style="margin-top:18px;margin-bottom:8px"><h2 style="font-size:14px">官方年度偏好书</h2><small>仅显示该年 API 返回的 preferBooks</small></div><div class="year-book-strip" id="yearBooks"></div></article>
'''

JS = r'''
const yearAnnual=Object.fromEntries((D.annual||[]).map(x=>[String(x.year),x]));
const yearFocus=Object.fromEntries((((D.insights||{}).focusShift)||[]).map(x=>[String(x.year),x]));
const yearList=[...new Set([...Object.keys(yearAnnual),...Object.keys(yearFocus),...(E.official?.annualPreferBooks||[]).map(x=>String(x.year||''))].filter(Boolean))].sort();
let activeYear=yearList[yearList.length-1]||'';
function renderYearLens(){const y=activeYear,a=yearAnnual[y]||{},f=yearFocus[y]||{},months=(D.monthly||[]).filter(x=>String(x.month||'').startsWith(y+'-'));const monthMap=Object.fromEntries(months.map(x=>[String(x.month).slice(5,7),x]));const maxH=Math.max(1,...months.map(x=>+x.hours||0));$('yearSwitch').innerHTML=yearList.map(v=>`<button class="year-btn ${v===y?'active':''}" data-year="${esc(v)}">${esc(v)}</button>`).join('');$('yearSwitch').querySelectorAll('button').forEach(b=>b.onclick=()=>{activeYear=b.dataset.year;renderYearLens()});const top=(f.topCategories||[])[0],topAuthor=(f.topAuthor||{}).author||'—',reviews=+f.reviews||0,notes=+f.notes||+a.notes||0;const kpis=[['阅读时长',Number(a.hours||0).toFixed(1)+'h'],['阅读天数',(a.days||0)+' 天'],['笔记',notes.toLocaleString()+' 条'],['本人想法',reviews.toLocaleString()+' 条'],['想法占比',Number(f.reviewRate||0).toFixed(1)+'%']];$('yearKpis').innerHTML=kpis.map(([k,v])=>`<div class="year-kpi"><span>${k}</span><b>${v}</b></div>`).join('');$('yearMonthBars').innerHTML=Array.from({length:12},(_,i)=>{const key=String(i+1).padStart(2,'0'),m=monthMap[key]||{},h=+m.hours||0,n=+m.notes||0;return `<div class="year-month-col"><div class="year-month-wrap"><div class="year-month-bar" style="height:${Math.max(2,100*h/maxH)}%"><span class="year-month-note">${n}</span><title>${y}-${key} · ${h.toFixed(1)}h · ${n} 条笔记</title></div></div><div class="year-month-val">${h?h.toFixed(0)+'h':''}</div><div class="year-month-lab">${i+1}月</div></div>`}).join('');$('yearFocus').innerHTML=(f.topCategories||[]).slice(0,5).map(x=>`<span class="year-focus-chip">${esc(x.category)} <b>${x.notes}</b> · ${x.share}%</span>`).join('')||'<span class="subtle">暂无类别时间证据</span>';const rising=(f.rising||[]).map(x=>`${x.category} +${x.delta}pp`).join('、')||'—',falling=(f.falling||[]).map(x=>`${x.category} ${x.delta}pp`).join('、')||'—';$('yearDetails').innerHTML=`<div class="year-detail-row"><span>年度关注最多</span><b>${top?esc(top.category):'—'}</b></div><div class="year-detail-row"><span>年度高频作者</span><b>${esc(topAuthor)}</b></div><div class="year-detail-row"><span>上升类别</span><b>${esc(rising)}</b></div><div class="year-detail-row"><span>回落类别</span><b>${esc(falling)}</b></div>`;const cards=(E.official?.annualPreferBooks||[]).filter(x=>String(x.year)===y);$('yearBooks').innerHTML=cards.length?cards.map(x=>`<div class="year-book-card"><div class="year-book-cover">${x.cover?`<img src="${esc(x.cover)}" loading="lazy" alt="">`:''}</div><b title="${esc(x.title)}">${esc(x.title||'—')}</b><small>${esc(x.author||'')}</small><em>${esc(x.label||'偏好书')}${x.reason?' · '+esc(x.reason):''}</em></div>`).join(''):'<span class="subtle">这一年没有缓存到官方偏好书卡。</span>';}if(yearList.length)renderYearLens();else optionalSection('year-lens',false);
'''
